### ISSUE TITLE
Fork & Refactor

### ISSUE THREAD

**Issue by alanshaw** [libp2p/hydra-booster#11]
- [x] Forked and renamed
- [x] Fill the README and link to the RFC (adding the logo) (@alanshaw)
- [x] Review and document the codebase
  - [x] Modularize/Packagerize the repo
    - [x] Part I (@daviddias)
    - [x] Part II (@daviddias) 
    - [x] Part III - Move runMany and runSingle to their separate files (@daviddias)
  - [x] Refactor
    - [x] error propagation (no panic(err)) (@alanshaw)
    - [x] strucs as opts (rather than a super long list of args) (@daviddias) https://github.com/libp2p/hydra-booster/pull/26
    - [x] extract http api into module (@alanshaw)
    - [x] extract ui from run-node.go (@alanshaw)

**Comment by daviddias** [comment]
This epic is aaaaaaalll done! 🎉

![](https://media.giphy.com/media/xT8qBt2943MLRO8zuM/giphy.gif)
